//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPracticeWPF.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academics
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Lastname { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Specialization { get; set; }
        public Nullable<int> YearOfAwardingTheTitle { get; set; }
    }
}
