//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPracticeWPF.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int Id { get; set; }
        public Nullable<int> CodeDiscipline { get; set; }
        public string NumberSpecialty { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Specialty Specialty { get; set; }
    }
}
