//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPracticeWPF.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Capital { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> Populace { get; set; }
        public string Continent { get; set; }
    }
}
