//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPracticeWPF.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engineer
    {
        public int Id { get; set; }
        public Nullable<int> TabNumberEmployee { get; set; }
        public string Specialty { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
